fpga: Kconfig: select CONFIG_DMA_SHARED_BUFFER
fpga_mgr uses dma-buf as well, so select the DMA_SHARED_BUFFER config
to fix below compilation errors that require this config enabled.

drivers/fpga/fpga-mgr.o: In function `fpga_dmabuf_fd_get':
/home/soceds/datastorm_daq/adrv9002_linux/drivers/fpga/fpga-mgr.c:693: undefined reference to `dma_buf_get'
drivers/fpga/fpga-mgr.o: In function `fpga_dmabuf_load':
/home/soceds/datastorm_daq/adrv9002_linux/drivers/fpga/fpga-mgr.c:315: undefined reference to `dma_buf_attach'
/home/soceds/datastorm_daq/adrv9002_linux/drivers/fpga/fpga-mgr.c:322: undefined reference to `dma_buf_map_attachment'
/home/soceds/datastorm_daq/adrv9002_linux/drivers/fpga/fpga-mgr.c:330: undefined reference to `dma_buf_unmap_attachment'
/home/soceds/datastorm_daq/adrv9002_linux/drivers/fpga/fpga-mgr.c:333: undefined reference to `dma_buf_detach'
/home/soceds/datastorm_daq/adrv9002_linux/drivers/fpga/fpga-mgr.c:335: undefined reference to `dma_buf_put'

Signed-off-by: d-samal <dibyajyoti.samal@einfochips.com>